version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: nobedevops/Dockerfile
    container_name: dev-env
    volumes:
      - .:/app
      - /app/nobedevops/node_modules
    working_dir: /app/nobedevops
    tty: true
    stdin_open: true
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
