services:
  app:
    image: node:20-alpine
    working_dir: /workspaces/NOBEDevOps/nobedevops
    volumes:
      - ..:/workspaces/NOBEDevOps:cached
      - nobedevops_node_modules:/workspaces/NOBEDevOps/nobedevops/node_modules
    command: sleep infinity
    ports:
      - "3000:3000"

volumes:
  nobedevops_node_modules: